server:
  port: 9401
spring:
  application:
    name: oauth2-jwt-service
  redis: #redis相关配置
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 2000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
      timeout: 1000 # 连接超时时间（毫秒）

